

spring:
  datasource:

      url: jdbc:mysql://localhost:3306/smgl?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: 'root'
      password: '20060602'
      driver-class-name: com.mysql.cj.jdbc.Driver


server:
  error:
    includeExceptions: true
    includStackTrace: always
    includeMessages: always
  port: 8080

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  type-aliases-package: wjx.bgs.vuespringbootmpkaoshi.pojo


mybatis:
  mapper-locations: classpath:mappers /*.xml
  type-aliases-package: wjx.bgs.vuespringbootmpkaoshi.pojo
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

